### ISSUE TITLE
Exception thrown on propietary driver

### ISSUE THREAD

**Issue by pemedina** [gamringer/php-pkcs11#65]
Hello:

I'm trying to use this module with a propietary pkcs11 provider (bit4id). This driver requires to open a session on a specific slot and create an object like :

```

$session = $module->openSession(ADMINSLOT , Pkcs11\CKF_RW_SESSION);

$object = $session->createObject([
  Pkcs11\CKA_CLASS => Pkcs11\CKO_DATA,
  Pkcs11\CKA_TOKEN => true,
  Pkcs11\CKA_PRIVATE => true,
  Pkcs11\CKA_ID => "login",
  Pkcs11\CKA_VALUE => "USER PASS",
]);
```

When i execute that code i recieve :
```
Fatal error: Uncaught Pkcs11\Exception: (0x00000082/CKR_OBJECT_HANDLE_INVALID) PKCS#11 module error: Unable to get attribute value in /Users/pemedina/projects/php-pkcs11/index.php:15
Stack trace:
#0 /Users/pemedina/projects/php-pkcs11/index.php(15): Pkcs11\Session->createObject(Array)
```

The weird thing is: if I enable DEBUG log mode in the driver i can see it connects properly to the HSM, the login is succesfull (it clearly says 200 ok) and the associated certificates are enumerated (due to the DEBUG mode), 
but, despite the ok response, the php exception is thrown.

For the records we have a golang wrapper that does the same thing and it works properly (so it is not a driver issue).

I wonder if there's a way to debug this specific exception . Any help will be appreciated.

**Comment by gamringer** [comment]
When creating an object, the code looks for the object class (CKA_CLASS) in order to return the correct PHP object type: 

Pkcs11\Key for the following:
CKO_PUBLIC_KEY
CKO_PRIVATE_KEY
CKO_SECRET_KEY
CKO_OTP_KEY
https://github.com/gamringer/php-pkcs11/blob/14cb4e8994eebc1dbbd55c9fed48ae8b947ce2da/pkcs11session.c#L584-L592


Pkcs11\Object for the the rest.
https://github.com/gamringer/php-pkcs11/blob/14cb4e8994eebc1dbbd55c9fed48ae8b947ce2da/pkcs11session.c#L596-L602

To do so, it calls into `getObjectClass`
https://github.com/gamringer/php-pkcs11/blob/14cb4e8994eebc1dbbd55c9fed48ae8b947ce2da/pkcs11session.c#L582

Inside `getObjectClass`, we get the CKA_CLASS, but it seems as though by that time, `CK_OBJECT_HANDLE_PTR hObject` that was passed as argument is no longer referencing the object that we just created.
https://github.com/gamringer/php-pkcs11/blob/14cb4e8994eebc1dbbd55c9fed48ae8b947ce2da/pkcs11.c#L177-L191

**Comment by pemedina** [comment]
Thanks for your reply.

We're currently trying to debug our setup with the info provided.
